{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-plot-common-portable/1.0-SNAPSHOT/visualization-plot-common-portable-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-common-portable",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "visualization-plot-common-portable-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-common-portable-jvm-1.0-SNAPSHOT.jar",
          "size": 113893,
          "sha1": "b6dbabf7b5a9916f5ab9a9562d8f8d0ae40f8e84",
          "md5": "6183436ed805ca5ed7d50c9a0e859c95"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-plot-common-portable-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-common-portable-jvm-1.0-SNAPSHOT.jar",
          "size": 113893,
          "sha1": "b6dbabf7b5a9916f5ab9a9562d8f8d0ae40f8e84",
          "md5": "6183436ed805ca5ed7d50c9a0e859c95"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-plot-common-portable-metadata/1.0-SNAPSHOT/visualization-plot-common-portable-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-plot-common-portable-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
