{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-base-svg-mapper-batik/1.0-SNAPSHOT/visualization-base-svg-mapper-batik-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-base-svg-mapper-batik",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "aq3ilnhwhfe4plknbuylqngpsy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "visualization-base-svg-mapper-batik-metadata-1.0-SNAPSHOT.jar",
          "url": "visualization-base-svg-mapper-batik-metadata-1.0-SNAPSHOT.jar",
          "size": 261,
          "sha1": "d248c2f8aeaababe0bd674409dc6dd9badcdfcf7",
          "md5": "d30228aae67fe5efc799d46199f3bdcf"
        }
      ]
    }
  ]
}
