{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-base-svg/1.0-SNAPSHOT/visualization-base-svg-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-base-svg",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "aq3ilnhwhfe4plknbuylqngpsy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "visualization-base-svg-js-1.0-SNAPSHOT.jar",
          "url": "visualization-base-svg-js-1.0-SNAPSHOT.jar",
          "size": 56863,
          "sha1": "8f851f7478e698a3d46d327d3d9f007ca3d8392f",
          "md5": "893ef16fb9cb58ad436f685426373cc0"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-base-svg-js-1.0-SNAPSHOT.jar",
          "url": "visualization-base-svg-js-1.0-SNAPSHOT.jar",
          "size": 56863,
          "sha1": "8f851f7478e698a3d46d327d3d9f007ca3d8392f",
          "md5": "893ef16fb9cb58ad436f685426373cc0"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-base-svg-metadata/1.0-SNAPSHOT/visualization-base-svg-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-base-svg-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
