{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-plot-builder/1.0-SNAPSHOT/visualization-plot-builder-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-builder",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "vzr3wimzjjgbldoxgqoppzw3zy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "visualization-plot-builder-metadata-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-builder-metadata-1.0-SNAPSHOT.jar",
          "size": 160111,
          "sha1": "e6c223c25e59946a2d87eb0ce749b6c98b9e370f",
          "md5": "ef85c477bfcaa0324ce869fb8166ec3a"
        }
      ]
    }
  ]
}
