{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-plot-base-portable/1.0-SNAPSHOT/visualization-plot-base-portable-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-base-portable",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "visualization-plot-base-portable-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-base-portable-jvm-1.0-SNAPSHOT.jar",
          "size": 439655,
          "sha1": "6aa2c14a8c05a5da786860d56c934b48c4ce41a0",
          "md5": "83b4556be738c9095394bb060ec830c9"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-common",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-common-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-plot-base-portable-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-base-portable-jvm-1.0-SNAPSHOT.jar",
          "size": 439655,
          "sha1": "6aa2c14a8c05a5da786860d56c934b48c4ce41a0",
          "md5": "83b4556be738c9095394bb060ec830c9"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-plot-base-portable-metadata/1.0-SNAPSHOT/visualization-plot-base-portable-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-plot-base-portable-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
