{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-plot-common/1.0-SNAPSHOT/visualization-plot-common-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-common",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "aq3ilnhwhfe4plknbuylqngpsy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "visualization-plot-common-js-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-common-js-1.0-SNAPSHOT.jar",
          "size": 43001,
          "sha1": "d1ae8b58e3b874b7f204e673e9f91b4107d8217d",
          "md5": "bd4f2a89777feb149b0b40333a0ef8c8"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-plot-common-js-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-common-js-1.0-SNAPSHOT.jar",
          "size": 43001,
          "sha1": "d1ae8b58e3b874b7f204e673e9f91b4107d8217d",
          "md5": "bd4f2a89777feb149b0b40333a0ef8c8"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-plot-common-metadata/1.0-SNAPSHOT/visualization-plot-common-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-plot-common-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
