{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-plot-common/1.0-SNAPSHOT/visualization-plot-common-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-common",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "visualization-plot-common-js-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-common-js-1.0-SNAPSHOT.jar",
          "size": 12986,
          "sha1": "308276f736f611a2dc2c7c9336721d0369d368b2",
          "md5": "fe1cb2f8f217a29e21cc3af17b877ab0"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-common-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-plot-common-js-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-common-js-1.0-SNAPSHOT.jar",
          "size": 12986,
          "sha1": "308276f736f611a2dc2c7c9336721d0369d368b2",
          "md5": "fe1cb2f8f217a29e21cc3af17b877ab0"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-plot-common-metadata/1.0-SNAPSHOT/visualization-plot-common-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-plot-common-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
