{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-plot-builder/1.0-SNAPSHOT/visualization-plot-builder-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-builder",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "vzr3wimzjjgbldoxgqoppzw3zy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "visualization-plot-builder-js-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-builder-js-1.0-SNAPSHOT.jar",
          "size": 207004,
          "sha1": "f83740a3ac12fe6e67a91f09682228b00291bfb0",
          "md5": "7dc33bdd867afeda44e673c8b9f8646f"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-js",
          "version": {
            "requires": "1.6.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-canvas",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-common",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-common",
          "version": {
            "requires": "1.6.24"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-plot-builder-js-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-builder-js-1.0-SNAPSHOT.jar",
          "size": 207004,
          "sha1": "f83740a3ac12fe6e67a91f09682228b00291bfb0",
          "md5": "7dc33bdd867afeda44e673c8b9f8646f"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-plot-builder-metadata/1.0-SNAPSHOT/visualization-plot-builder-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-plot-builder-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
