{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-plot-common/1.0-SNAPSHOT/visualization-plot-common-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-common",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "vzr3wimzjjgbldoxgqoppzw3zy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "visualization-plot-common-metadata-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-common-metadata-1.0-SNAPSHOT.jar",
          "size": 21006,
          "sha1": "e463793cff259212af6ce6af30843cde7d761095",
          "md5": "5db920fe268ad6ae6275707e32c75aed"
        }
      ]
    }
  ]
}
