{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-plot-common/1.0-SNAPSHOT/visualization-plot-common-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-common",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "visualization-plot-common-metadata-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-common-metadata-1.0-SNAPSHOT.jar",
          "size": 2348,
          "sha1": "1ad6ae697852e8b9221ee448f3c70e623aac1c3f",
          "md5": "1e4cd88e2977a00643428a6ec945b5a1"
        }
      ]
    }
  ]
}
