{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-base-svg/1.0-SNAPSHOT/visualization-base-svg-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-base-svg",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "aq3ilnhwhfe4plknbuylqngpsy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "visualization-base-svg-metadata-1.0-SNAPSHOT.jar",
          "url": "visualization-base-svg-metadata-1.0-SNAPSHOT.jar",
          "size": 41382,
          "sha1": "2694146b11fdafcac68d4d115c82db14ffebcc8a",
          "md5": "ae231f555641d616082c4dcdf7ec4ef0"
        }
      ]
    }
  ]
}
