{
  "formatVersion": "0.4",
  "component": {
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-builder",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../visualization-plot-builder-js/1.0-SNAPSHOT/visualization-plot-builder-js-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-plot-builder-js",
        "version": "1.0-SNAPSHOT"
      }
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../visualization-plot-builder-js/1.0-SNAPSHOT/visualization-plot-builder-js-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-plot-builder-js",
        "version": "1.0-SNAPSHOT"
      }
    },
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../visualization-plot-builder-jvm/1.0-SNAPSHOT/visualization-plot-builder-jvm-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-plot-builder-jvm",
        "version": "1.0-SNAPSHOT"
      }
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../visualization-plot-builder-jvm/1.0-SNAPSHOT/visualization-plot-builder-jvm-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-plot-builder-jvm",
        "version": "1.0-SNAPSHOT"
      }
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-plot-builder-metadata/1.0-SNAPSHOT/visualization-plot-builder-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-plot-builder-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
