{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-plot-base/1.0-SNAPSHOT/visualization-plot-base-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-base",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "visualization-plot-base-metadata-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-base-metadata-1.0-SNAPSHOT.jar",
          "size": 61183,
          "sha1": "ebd3506651586e6c4bb2285f8134251d90ec3a51",
          "md5": "d2c9e50cd2084515bf992c5d678c382d"
        }
      ]
    }
  ]
}
