{
  "formatVersion": "0.4",
  "component": {
    "url": "../../datalore-plot-jfx/1.0-SNAPSHOT/datalore-plot-jfx-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "datalore-plot-jfx",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "mapper-core",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-canvas",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg-mapper",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg-mapper-jfx",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-base-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-common-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-common",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-builder-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-builder",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-config-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-config",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-demo-common",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-demo-common-jfx",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-jfx-package-metadata-1.0-SNAPSHOT.jar",
          "url": "datalore-plot-metadata-jfx-1.0-SNAPSHOT.jar",
          "size": 261,
          "sha1": "61e57668bae31c993d4ce97081aa86d5826de17",
          "md5": "e7ad1a1b5d91dbe22d59131862a98afa"
        }
      ]
    }
  ]
}
