package org.jetbrains.letsPlot.bistro.waterfall

fun waterfallPlot(
    data: Map<*, *>,
    x: String,
    y: String,
    measure: String? = null,
    group: String? = null,
    color: String? = null,
    fill: String? = null,
    size: Double? = null,
    alpha: Double? = null,
    lineType: Any? = null,
    width: Double? = null,
    showLegend: Boolean? = null,
    relativeTooltips: Any? = null,
    absoluteTooltips: Any? = null,
    calcTotal: Boolean? = null,
    totalTitle: String? = null,
    sortedValue: Boolean? = null,
    threshold: Double? = null,
    maxValues: Int? = null,
    hLine: Any? = null,
    hLineOnTop: Boolean? = null,
    connector: Any? = null,
    label: Any? = null,
    labelFormat: String? = null
) = WaterfallPlotBuilder(
    data = data,
    x = x,
    y = y,
    measure = measure,
    group = group,
    color = color,
    fill = fill,
    size = size,
    alpha = alpha,
    lineType = lineType,
    width = width,
    showLegend = showLegend,
    relativeTooltips = relativeTooltips,
    absoluteTooltips = absoluteTooltips,
    calcTotal = calcTotal,
    totalTitle = totalTitle,
    sortedValue = sortedValue,
    threshold = threshold,
    maxValues = maxValues,
    hLine = hLine,
    hLineOnTop = hLineOnTop,
    connector = connector,
    label = label,
    labelFormat = labelFormat
).build()