{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-base-svg-mapper/1.0-SNAPSHOT/visualization-base-svg-mapper-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-base-svg-mapper",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "aq3ilnhwhfe4plknbuylqngpsy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "visualization-base-svg-mapper-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-base-svg-mapper-jvm-1.0-SNAPSHOT.jar",
          "size": 10982,
          "sha1": "5b830a7eb3714e021f16ecf9e2bf358cc1e6119c",
          "md5": "ecf20b02c9dca9cca7e5dfc75e39cfcf"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "mapper-core",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-base-svg-mapper-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-base-svg-mapper-jvm-1.0-SNAPSHOT.jar",
          "size": 10982,
          "sha1": "5b830a7eb3714e021f16ecf9e2bf358cc1e6119c",
          "md5": "ecf20b02c9dca9cca7e5dfc75e39cfcf"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-base-svg-mapper-metadata/1.0-SNAPSHOT/visualization-base-svg-mapper-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-base-svg-mapper-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
