{
  "formatVersion": "0.4",
  "component": {
    "url": "../../mapper-core/1.0-SNAPSHOT/mapper-core-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "mapper-core",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "vzr3wimzjjgbldoxgqoppzw3zy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "mapper-core-js-1.0-SNAPSHOT.jar",
          "url": "mapper-core-js-1.0-SNAPSHOT.jar",
          "size": 19794,
          "sha1": "9a72d19c248ad855b2f00491da89c5ae8face680",
          "md5": "c337a23a964ff2442a60253e1eacace8"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "mapper-core-js-1.0-SNAPSHOT.jar",
          "url": "mapper-core-js-1.0-SNAPSHOT.jar",
          "size": 19794,
          "sha1": "9a72d19c248ad855b2f00491da89c5ae8face680",
          "md5": "c337a23a964ff2442a60253e1eacace8"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../mapper-core-metadata/1.0-SNAPSHOT/mapper-core-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "mapper-core-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
