{
  "formatVersion": "0.4",
  "component": {
    "url": "../../mapper-core/1.0-SNAPSHOT/mapper-core-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "mapper-core",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "aq3ilnhwhfe4plknbuylqngpsy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mapper-core-jvm-1.0-SNAPSHOT.jar",
          "url": "mapper-core-jvm-1.0-SNAPSHOT.jar",
          "size": 84256,
          "sha1": "8547a8c4b347c382ed2a65668764a2d31ad8caba",
          "md5": "744b8547caf8958b391e33d529758077"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.6.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "mapper-core-jvm-1.0-SNAPSHOT.jar",
          "url": "mapper-core-jvm-1.0-SNAPSHOT.jar",
          "size": 84256,
          "sha1": "8547a8c4b347c382ed2a65668764a2d31ad8caba",
          "md5": "744b8547caf8958b391e33d529758077"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../mapper-core-metadata/1.0-SNAPSHOT/mapper-core-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "mapper-core-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
