{
  "formatVersion": "0.4",
  "component": {
    "url": "../../mapper-core/1.0-SNAPSHOT/mapper-core-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "mapper-core",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mapper-core-jvm-1.0-SNAPSHOT.jar",
          "url": "mapper-core-jvm-1.0-SNAPSHOT.jar",
          "size": 83154,
          "sha1": "6432fef5c26fb225af43443f7bdb1fcd7cdd8b39",
          "md5": "4d863db0effb0bfea75dda4a10082274"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-common",
          "version": {
            "requires": "1.7.6"
          }
        }
      ],
      "files": [
        {
          "name": "mapper-core-jvm-1.0-SNAPSHOT.jar",
          "url": "mapper-core-jvm-1.0-SNAPSHOT.jar",
          "size": 83154,
          "sha1": "6432fef5c26fb225af43443f7bdb1fcd7cdd8b39",
          "md5": "4d863db0effb0bfea75dda4a10082274"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../mapper-core-metadata/1.0-SNAPSHOT/mapper-core-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "mapper-core-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
