{
  "formatVersion": "0.4",
  "component": {
    "url": "../../base-portable/1.0-SNAPSHOT/base-portable-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "base-portable",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "base-portable-jvm-1.0-SNAPSHOT.jar",
          "url": "base-portable-jvm-1.0-SNAPSHOT.jar",
          "size": 272117,
          "sha1": "6254fed1305dc557bd92371b016c2335ae8d2d76",
          "md5": "4c9d35be3d64b7f908e820547de367a9"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-common",
          "version": {
            "requires": "1.7.6"
          }
        }
      ],
      "files": [
        {
          "name": "base-portable-jvm-1.0-SNAPSHOT.jar",
          "url": "base-portable-jvm-1.0-SNAPSHOT.jar",
          "size": 272117,
          "sha1": "6254fed1305dc557bd92371b016c2335ae8d2d76",
          "md5": "4c9d35be3d64b7f908e820547de367a9"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../base-portable-metadata/1.0-SNAPSHOT/base-portable-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "base-portable-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
