{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-base-svg/1.0-SNAPSHOT/visualization-base-svg-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-base-svg",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "vzr3wimzjjgbldoxgqoppzw3zy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "visualization-base-svg-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-base-svg-jvm-1.0-SNAPSHOT.jar",
          "size": 178727,
          "sha1": "208accf62bb185bc243c3b0e40367c328a970926",
          "md5": "590b7f4a10c1ee2a500b36e4ff8814a2"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-base-svg-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-base-svg-jvm-1.0-SNAPSHOT.jar",
          "size": 178727,
          "sha1": "208accf62bb185bc243c3b0e40367c328a970926",
          "md5": "590b7f4a10c1ee2a500b36e4ff8814a2"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-base-svg-metadata/1.0-SNAPSHOT/visualization-base-svg-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-base-svg-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
