{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-base-canvas/1.0-SNAPSHOT/visualization-base-canvas-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-base-canvas",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "aq3ilnhwhfe4plknbuylqngpsy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "visualization-base-canvas-js-1.0-SNAPSHOT.jar",
          "url": "visualization-base-canvas-js-1.0-SNAPSHOT.jar",
          "size": 36728,
          "sha1": "cf7d373d9a078a9e4d4c3e0ca5c7eb020305884e",
          "md5": "8b7c5aa27bcdf93f9adcd0a8a0cdd345"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-base-canvas-js-1.0-SNAPSHOT.jar",
          "url": "visualization-base-canvas-js-1.0-SNAPSHOT.jar",
          "size": 36728,
          "sha1": "cf7d373d9a078a9e4d4c3e0ca5c7eb020305884e",
          "md5": "8b7c5aa27bcdf93f9adcd0a8a0cdd345"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-base-canvas-metadata/1.0-SNAPSHOT/visualization-base-canvas-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-base-canvas-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
