{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-base-canvas/1.0-SNAPSHOT/visualization-base-canvas-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-base-canvas",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "vzr3wimzjjgbldoxgqoppzw3zy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "visualization-base-canvas-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-base-canvas-jvm-1.0-SNAPSHOT.jar",
          "size": 147420,
          "sha1": "7a59d3ff9833d5396feed9402bddf0209b128d4d",
          "md5": "8658d59af2b7d3e01d6eb50508248de7"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-base-canvas-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-base-canvas-jvm-1.0-SNAPSHOT.jar",
          "size": 147420,
          "sha1": "7a59d3ff9833d5396feed9402bddf0209b128d4d",
          "md5": "8658d59af2b7d3e01d6eb50508248de7"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-base-canvas-metadata/1.0-SNAPSHOT/visualization-base-canvas-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-base-canvas-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
