{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-base-canvas/1.0-SNAPSHOT/visualization-base-canvas-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-base-canvas",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "visualization-base-canvas-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-base-canvas-jvm-1.0-SNAPSHOT.jar",
          "size": 152144,
          "sha1": "cd288ce9af6c253a95f73760a99a9fcca2344756",
          "md5": "767b2ea55d028155c1cdfe462f5e171"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-base-canvas-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-base-canvas-jvm-1.0-SNAPSHOT.jar",
          "size": 152144,
          "sha1": "cd288ce9af6c253a95f73760a99a9fcca2344756",
          "md5": "767b2ea55d028155c1cdfe462f5e171"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-base-canvas-metadata/1.0-SNAPSHOT/visualization-base-canvas-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-base-canvas-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
