{
  "formatVersion": "0.4",
  "component": {
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-base-svg-mapper-batik",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "vzr3wimzjjgbldoxgqoppzw3zy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../visualization-base-svg-mapper-batik-jvm/1.0-SNAPSHOT/visualization-base-svg-mapper-batik-jvm-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-base-svg-mapper-batik-jvm",
        "version": "1.0-SNAPSHOT"
      }
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../visualization-base-svg-mapper-batik-jvm/1.0-SNAPSHOT/visualization-base-svg-mapper-batik-jvm-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-base-svg-mapper-batik-jvm",
        "version": "1.0-SNAPSHOT"
      }
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-base-svg-mapper-batik-metadata/1.0-SNAPSHOT/visualization-base-svg-mapper-batik-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-base-svg-mapper-batik-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
