{
  "formatVersion": "0.4",
  "component": {
    "url": "../../mapper-core/1.0-SNAPSHOT/mapper-core-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "mapper-core",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "vzr3wimzjjgbldoxgqoppzw3zy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "mapper-core-metadata-1.0-SNAPSHOT.jar",
          "url": "mapper-core-metadata-1.0-SNAPSHOT.jar",
          "size": 14153,
          "sha1": "29b698f308c6cddabfe08ad09d68cea574be3bc4",
          "md5": "ffcc28c7ab49ad5abbb9d2f7e09b581f"
        }
      ]
    }
  ]
}
