{
  "formatVersion": "0.4",
  "component": {
    "url": "../../mapper-core/1.0-SNAPSHOT/mapper-core-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "mapper-core",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "mapper-core-metadata-1.0-SNAPSHOT.jar",
          "url": "mapper-core-metadata-1.0-SNAPSHOT.jar",
          "size": 14139,
          "sha1": "69d5753b5a6c3c7f3a8b60bf26f0c7a832cbb5a",
          "md5": "52ec329593223de07edc8e527f1fd687"
        }
      ]
    }
  ]
}
