{
  "formatVersion": "0.4",
  "component": {
    "url": "../../base/1.0-SNAPSHOT/base-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "base",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "vzr3wimzjjgbldoxgqoppzw3zy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "base-metadata-1.0-SNAPSHOT.jar",
          "url": "base-metadata-1.0-SNAPSHOT.jar",
          "size": 103709,
          "sha1": "697421d956c9ac561890f27f617773ee0e135965",
          "md5": "6321ecbe9b5027499f829e2f2378e744"
        }
      ]
    }
  ]
}
