{
  "formatVersion": "0.4",
  "component": {
    "url": "../../base/1.0-SNAPSHOT/base-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "base",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "base-metadata-1.0-SNAPSHOT.jar",
          "url": "base-metadata-1.0-SNAPSHOT.jar",
          "size": 69287,
          "sha1": "d424628c9c3e1ddeaf620ce9ba31d67b47be05bc",
          "md5": "633ad527d0f1b8aa058257fb4f0686c7"
        }
      ]
    }
  ]
}
