{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-plot-common/1.0-SNAPSHOT/visualization-plot-common-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-common",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "vzr3wimzjjgbldoxgqoppzw3zy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "visualization-plot-common-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-common-jvm-1.0-SNAPSHOT.jar",
          "size": 120369,
          "sha1": "51966ac713007d33d9d5b514ff59825e57b00d8a",
          "md5": "5dfab58bab13125df82f9d035d455c71"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-plot-common-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-common-jvm-1.0-SNAPSHOT.jar",
          "size": 120369,
          "sha1": "51966ac713007d33d9d5b514ff59825e57b00d8a",
          "md5": "5dfab58bab13125df82f9d035d455c71"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-plot-common-metadata/1.0-SNAPSHOT/visualization-plot-common-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-plot-common-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
