{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-plot-common/1.0-SNAPSHOT/visualization-plot-common-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-common",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "visualization-plot-common-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-common-jvm-1.0-SNAPSHOT.jar",
          "size": 5297,
          "sha1": "38be4c6ed5aed53f6bcf4920ed90030f0551f494",
          "md5": "90ccf473e809bd889e4bd1a4f9dbde7a"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-common-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-plot-common-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-common-jvm-1.0-SNAPSHOT.jar",
          "size": 5297,
          "sha1": "38be4c6ed5aed53f6bcf4920ed90030f0551f494",
          "md5": "90ccf473e809bd889e4bd1a4f9dbde7a"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-plot-common-metadata/1.0-SNAPSHOT/visualization-plot-common-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-plot-common-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
