{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-plot-config-portable-macosx64/1.0-SNAPSHOT/visualization-plot-config-portable-macosx64-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-config-portable-macosx64",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "visualization-plot-config-portable-metadata-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-config-portable-metadata-1.0-SNAPSHOT.jar",
          "size": 39925,
          "sha1": "65f309b40424df6307aaeaabec0245d401786df1",
          "md5": "c44f6123e200f1cca16fd2e8492c8282"
        }
      ]
    }
  ]
}
