{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-base-svg-mapper-batik/1.0-SNAPSHOT/visualization-base-svg-mapper-batik-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-base-svg-mapper-batik",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "vzr3wimzjjgbldoxgqoppzw3zy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-anim",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-awt-util",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-css",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-ext",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-gvt",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-parser",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-script",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svg-dom",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-swing",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-util",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-xml",
          "version": {
            "requires": "1.7"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-base-svg-mapper-batik-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-base-svg-mapper-batik-jvm-1.0-SNAPSHOT.jar",
          "size": 57809,
          "sha1": "7c49090baba67b3cb1b260c93a3a0d1239410585",
          "md5": "aff18a9213b7fb6ad091fb3fb1870f07"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-anim",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-awt-util",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-codec",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-css",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-dom",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-ext",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-gvt",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-parser",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-script",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svg-dom",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-swing",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-util",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-xml",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg-mapper",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "mapper-core",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-base-svg-mapper-batik-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-base-svg-mapper-batik-jvm-1.0-SNAPSHOT.jar",
          "size": 57809,
          "sha1": "7c49090baba67b3cb1b260c93a3a0d1239410585",
          "md5": "aff18a9213b7fb6ad091fb3fb1870f07"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-base-svg-mapper-batik-metadata/1.0-SNAPSHOT/visualization-base-svg-mapper-batik-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-base-svg-mapper-batik-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
