{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-demo-common-jfx/1.0-SNAPSHOT/visualization-demo-common-jfx-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-demo-common-jfx",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-demo-common",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-demo-common-jfx-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-demo-common-jfx-jvm-1.0-SNAPSHOT.jar",
          "size": 28598,
          "sha1": "6d16991fe26d51720bc48de7c6e714c684d639fa",
          "md5": "fbeb1b8766a9f6bc473cc51f5a9678c4"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-demo-common",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-canvas",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg-mapper-jfx",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "mapper-core",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-demo-common-jfx-jvm-1.0-SNAPSHOT.jar",
          "url": "visualization-demo-common-jfx-jvm-1.0-SNAPSHOT.jar",
          "size": 28598,
          "sha1": "6d16991fe26d51720bc48de7c6e714c684d639fa",
          "md5": "fbeb1b8766a9f6bc473cc51f5a9678c4"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-demo-common-jfx-metadata/1.0-SNAPSHOT/visualization-demo-common-jfx-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-demo-common-jfx-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
