{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-demo-common/1.0-SNAPSHOT/visualization-demo-common-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-demo-common",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "visualization-demo-common-js-1.0-SNAPSHOT.jar",
          "url": "visualization-demo-common-js-1.0-SNAPSHOT.jar",
          "size": 65192,
          "sha1": "a90e75aff492ff42828e35ae5bc6329060ebebd4",
          "md5": "ac19f92e31ffbf2ef95508ec26c1d8ae"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-demo-common-js-1.0-SNAPSHOT.jar",
          "url": "visualization-demo-common-js-1.0-SNAPSHOT.jar",
          "size": 65192,
          "sha1": "a90e75aff492ff42828e35ae5bc6329060ebebd4",
          "md5": "ac19f92e31ffbf2ef95508ec26c1d8ae"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-demo-common-metadata/1.0-SNAPSHOT/visualization-demo-common-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-demo-common-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
