{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-demo-common-jfx/1.0-SNAPSHOT/visualization-demo-common-jfx-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-demo-common-jfx",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-demo-common",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-demo-common-jfx-js-1.0-SNAPSHOT.jar",
          "url": "visualization-demo-common-jfx-js-1.0-SNAPSHOT.jar",
          "size": 261,
          "sha1": "3137614d4e8714c17189671e314cedba3c21c2be",
          "md5": "dbd19dee19cb9ded6b8f2ea036d6c7ce"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-demo-common",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "mapper-core",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-demo-common-jfx-js-1.0-SNAPSHOT.jar",
          "url": "visualization-demo-common-jfx-js-1.0-SNAPSHOT.jar",
          "size": 261,
          "sha1": "3137614d4e8714c17189671e314cedba3c21c2be",
          "md5": "dbd19dee19cb9ded6b8f2ea036d6c7ce"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-demo-common-jfx-metadata/1.0-SNAPSHOT/visualization-demo-common-jfx-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-demo-common-jfx-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
