{
  "formatVersion": "0.4",
  "component": {
    "url": "../../base/1.0-SNAPSHOT/base-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "base",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.2",
      "buildId": "ne73s3woxzcojp4j2clll2tc3a"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "base-js-1.0-SNAPSHOT.jar",
          "url": "base-js-1.0-SNAPSHOT.jar",
          "size": 275537,
          "sha1": "5eadfdf698ad00fb5995a245a11a351b4d15361",
          "md5": "eb62991a3d3c2dbab01c7395d999bf61"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-js",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-common",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base-portable",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "base-js-1.0-SNAPSHOT.jar",
          "url": "base-js-1.0-SNAPSHOT.jar",
          "size": 275537,
          "sha1": "5eadfdf698ad00fb5995a245a11a351b4d15361",
          "md5": "eb62991a3d3c2dbab01c7395d999bf61"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../base-metadata/1.0-SNAPSHOT/base-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "base-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
