{
  "formatVersion": "0.4",
  "component": {
    "url": "../../base/1.0-SNAPSHOT/base-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "base",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "aq3ilnhwhfe4plknbuylqngpsy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.7"
          }
        }
      ],
      "files": [
        {
          "name": "base-jvm-1.0-SNAPSHOT.jar",
          "url": "base-jvm-1.0-SNAPSHOT.jar",
          "size": 630249,
          "sha1": "4ffa734124736a94a9f145d91b71f3404c07b77c",
          "md5": "5f7a9b3996d9bdfa52d5d80deea0efda"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.30"
          }
        }
      ],
      "files": [
        {
          "name": "base-jvm-1.0-SNAPSHOT.jar",
          "url": "base-jvm-1.0-SNAPSHOT.jar",
          "size": 630249,
          "sha1": "4ffa734124736a94a9f145d91b71f3404c07b77c",
          "md5": "5f7a9b3996d9bdfa52d5d80deea0efda"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../base-metadata/1.0-SNAPSHOT/base-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "base-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
