{
  "formatVersion": "0.4",
  "component": {
    "url": "../../visualization-plot-config/1.0-SNAPSHOT/visualization-plot-config-1.0-SNAPSHOT.module",
    "group": "org.jetbrains.datalore-plot",
    "module": "visualization-plot-config",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.3",
      "buildId": "aq3ilnhwhfe4plknbuylqngpsy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "visualization-plot-config-js-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-config-js-1.0-SNAPSHOT.jar",
          "size": 88077,
          "sha1": "f43c7b8c03686029bc2e18eda7f883ab0464591d",
          "md5": "fcacf935cfe3e3ac50c0509d0029ded7"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-js",
          "version": {
            "requires": "1.6.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "prefers": "1.3.30"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-svg",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-base-canvas",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-base",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-common",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.datalore-plot",
          "module": "visualization-plot-builder",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-common",
          "version": {
            "requires": "1.6.24"
          }
        }
      ],
      "files": [
        {
          "name": "visualization-plot-config-js-1.0-SNAPSHOT.jar",
          "url": "visualization-plot-config-js-1.0-SNAPSHOT.jar",
          "size": 88077,
          "sha1": "f43c7b8c03686029bc2e18eda7f883ab0464591d",
          "md5": "fcacf935cfe3e3ac50c0509d0029ded7"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../visualization-plot-config-metadata/1.0-SNAPSHOT/visualization-plot-config-metadata-1.0-SNAPSHOT.module",
        "group": "org.jetbrains.datalore-plot",
        "module": "visualization-plot-config-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
